/**
 * Copyright 2014. Intellect Design Arena Limited. All rights reserved. 
 * 
 * These materials are confidential and proprietary to Intellect Design Arena 
 * Limited and no part of these materials should be reproduced, published, transmitted
 * or distributed in any form or by any means, electronic, mechanical, photocopying, 
 * recording or otherwise, or stored in any information storage or retrieval system 
 * of any nature nor should the materials be disclosed to third parties or used in any 
 * other manner for which this is not authorized, without the prior express written 
 * authorization of Intellect Design Arena Limited.
 * 
 */

/**
 * This file is generated by CodeGenerator version = 1.0
 **/
package com.intellectdesign.canvas.constants.notes;

/**
 * This class contains the Notes Constants
 * 
 * @version 1.0
 */

/**
 * NotesConstants maintains all the constants used across the cuser related classes.
 */

public class NotesConstants
{

	/**
	 * Private constructor prevents object construction outside this class.
	 */

	private NotesConstants()
	{
		/**
		 * ref to NotesConstants actions,fields, Private cnstructor to avoid instantiation.
		 */
	}

	public static final String ACTION_INIT_ACTION = "INIT_ACTION";
	public static final String INPUT_PRODUCT = "INPUT_PRODUCT";
	public static final String SUCCESS_MSG_KEY = "SUCCESS_MSG_KEY";
	public static final String FAILURE_MSG_KEY = "FAILURE_MSG_KEY";
	public static final String ERROR = "ERROR";

	public final static String STATUS = "STATUS";

	// Define the list of fields that are present in the DAM layer
	public static final String FIELD_OD_GCIF = "OD_GCIF";
	public static final String FIELD_MESSAGE = "MESSAGE";
	public static final String FIELD_NOTES_DATE = "NOTES_DATE";
	public static final String FIELD_MAKER_ID = "MAKER_ID";
	public static final String FIELD_MAKER_DT = "MAKER_DT";
	public static final String FIELD_AUTH_ID = "AUTH_ID";
	public static final String FIELD_AUTH_DT = "AUTH_DT";
	public static final String FIELD_VERSION_NO = "VERSION_NO";
	public static final String FIELD_OD_USER_NO = "OD_USER_NO";
	public static final String SORT_DESC = "DESC";
	public static final String SORT_ASC = "ASC";
	public static final String DEFAULT_SORTING_ORDER = SORT_ASC;
	public static final String NOTES_DAM = "NOTES_DAM";
	public static final String NOTES_DAM_SEQ = "NOTES_DAM_SEQ";
	public static final String NOTES_DAM_LIB_DETAILS_MNT = "NOTES_DAM_LIB_DETAILS_MNT";
	public static final String NOTES_DAM_DTLS = "NOTES_DAM_DTLS";
	public static final String NOTES_DAM_STATUS = "NOTES_DAM_STATUS";

	public static final String SAVE_NOTE = "SAVE_NOTE";
	public static final String SEND_NOTE = "SEND_NOTE";
	public static final String LOAD_NOTE = "LOAD_NOTE";

}
